name: sixam_mart
description: A Multi-vendor Food. Grocery, eCommerce, Pharmacy & Parcel service.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  shared_preferences: ^2.0.11
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  pin_code_fields: ^8.0.1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.1.5
  google_maps_flutter_web: ^0.5.8
  flutter_typeahead: ^5.2.0
  carousel_slider: ^4.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: ^1.1.2
  image_picker_ios: ^0.8.5+6
  universal_html: ^2.0.8
  flutter_inappwebview: ^6.0.0
  flutter_widget_from_html: ^0.15.0
  flutter_html: ^3.0.0-alpha.5
  url_launcher: ^6.1.2
  http: ^1.2.1
  pointer_interceptor: ^0.10.1+1
  phone_number: ^2.1.0
  country_code_picker: ^3.0.0
  cached_network_image: ^3.3.0
  photo_view: ^0.15.0
  flutter_image_compress: ^2.3.0
  dotted_border: ^2.0.0+1
  share_plus: ^9.0.0
  expandable_bottom_sheet: ^1.1.1+1
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4
  flutter_facebook_auth: ^7.0.0
  flutter_animarker: ^3.2.0
  sign_in_with_apple: ^6.1.0
  intl: ^0.19.0
  just_the_tooltip: ^0.0.12
  flutter_slidable: ^3.0.0
  meta_seo: ^3.0.5
  animated_flip_counter: ^0.3.4
  youtube_player_iframe: ^5.1.2
  card_swiper: ^3.0.1
  audioplayers: ^6.0.0
  change_app_package_name: ^1.2.0
  audio_session: ^0.1.19
  connectivity_plus: ^6.0.3

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900